// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClassLibrary.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        [Column("idCliente")]
        [Display(Name ="Código")]
        public int IdCliente { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("sobrenome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Sobrenome { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column("dataCadastro", TypeName = "datetime")]
        [Display(Name = "Data De Cadastro")]
        public DateTime DataCadastro { get; set; }
        [Column("ativo")]

        public bool Ativo { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}