// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClassLibrary.Models
{
    public partial class Produto
    {
        [Key]
        [Column("idProduto")]
        public int IdProduto { get; set; }
        [Required]
        [Column("nome")]
        [Display(Name = "Produto")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("valor")]
        public double Valor { get; set; }
        [Column("disponivel")]
        public bool Disponivel { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("Produto")]

        public virtual Cliente IdClienteNavigation { get; set; }
    }
}